# Generated by Django 3.2.3 on 2021-06-02 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 14, 36, 49, 847374, tzinfo=utc)),
        ),
    ]
