# Generated by Django 3.2.3 on 2021-06-02 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_payment', '0003_alter_records_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='time',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
