# Generated by Django 3.2.3 on 2021-06-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_payment', '0004_alter_records_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='order_id',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='records',
            name='org_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='records',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='records',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
