# Generated by Django 3.2.3 on 2021-06-03 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_payment', '0005_auto_20210603_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
